import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from './navbar/page';
import style2 from './page.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Creating Autchat",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     
     <body className={style2.container}>
     <NavBar></NavBar>
     
     {children}
     </body>
    </html>
  );
}
